service: sendS3Event
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: dev
  region: ap-south-1
  environment:
    basePath: ./
    API_ENDPOINT: ${env:API_ENDPOINT}
   

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
useDotenv: true

functions:
  function1:
    handler: index.handler
