service: video-transcoder
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: dev
  region: ap-south-1
  environment:
    basePath: ./
    MY_AWS_ACCESS_KEY_ID: ${env:MY_AWS_ACCESS_KEY_ID}
    MY_AWS_SECRET_ACCESS_KEY: ${env:MY_AWS_SECRET_ACCESS_KEY}
    REDIS_URL: ${env:REDIS_URL}
    MONGODB_URI: ${env:MONGODB_URI}
    S3_BUCKET: ${env:S3_BUCKET}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
useDotenv: true

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
